spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: jdbc:${DATABASE_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.gmail.com
    port: 587
    username: my.test.apps.04@gmail.com
    password: ${hidden.email.password}