spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:${DATABASE_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true
server:
  hostname: online-shop-iablonski.herokuapp.com
  port: ${PORT:8080}
mail:
  server:
    host: smtp.gmail.com
    port: 587
    username: ${hidden.email.username}
    password: ${hidden.email.password}